---
- name: install vim
  become: yes
  become_method: sudo
  become_user: root
  apt:
    name: vim
    state: latest
    update_cache: yes

- name: install visual studio code
  become: yes
  become_method: sudo
  become_user: root
  command: snap install --classic vscode

- name: install qt creator
  become: yes
  become_method: sudo
  become_user: root
  apt:
    name: qtcreator
    state: latest
    update_cache: yes
  when: project_language == "c++"

