---
- name: set up development environment for openmw
  hosts: localhost

  roles:
    - common
    - { role: editors, project_language: "c++" }

  tasks:
    - name: add openmw ppa
      become: yes
      become_method: sudo
      become_user: root
      apt_repository:
        repo: 'ppa:openmw/openmw'
        state: present

    - name: install project dependencies
      become: yes
      become_method: sudo
      become_user: root
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - build-essential
        - cmake
        - libavcodec-dev
        - libavformat-dev
        - libavutil-dev
        - libboost-filesystem-dev
        - libboost-program-options-dev
        - libboost-system-dev
        - libboost-thread-dev
        - libbullet-dev
        - libmygui-dev
        - libopenal-dev
        - libopenscenegraph-3.4-dev
        - libqt4-dev
        - libqt4-opengl-dev
        - libsdl2-dev
        - libswresample-dev
        - libswscale-dev
        - libunshield-dev

    - name: fetch openmw repo
      become: yes
      become_method: sudo
      become_user: "{{ project_user }}"
      git:
        repo: https://github.com/{{ git.username }}/openmw.git
        dest: "{{ ansible_env.HOME }}/Projects/openmw"

    - name: add upstream repo
      become: yes
      become_method: sudo
      become_user: "{{ project_user }}"
      shell: git remote add upstream https://github.com/openmw/openmw.git
      args:
        chdir: "{{ ansible_env.HOME }}/Projects/openmw"
      ignore_errors: yes

    - name: create directory for morrowind game files
      become: yes
      become_method: sudo
      become_user: "{{ project_user }}"
      file:
        path: "{{ ansible_env.HOME }}/Games"
        state: directory

    - name: check if morrowind game files exist
      become: yes
      become_method: sudo
      become_user: "{{ project_user }}"
      stat: path={{ ansible_env.HOME }}/Games/Morrowind
      register: game_files

    - name: download morrowind game files
      become: yes
      become_method: sudo
      become_user: "{{ project_user }}"
      get_url:
        url: "{{ urls.morrowind_game_files }}"
        dest: "{{ ansible_env.HOME }}/Games/morrowind-data.tar.gz"
        force: no
      when: game_files.stat.exists == False

    - name: unpack game files
      become: yes
      become_user: "{{ project_user }}"
      unarchive:
        src: "{{ ansible_env.HOME }}/Games/morrowind-data.tar.gz"
        dest: "{{ ansible_env.HOME }}/Games"
        creates: "{{ ansible_env.HOME }}/Games/Morrowind"
      when: game_files.stat.exists == False

